### ISSUE TITLE
notify the user with tips for right eating behavior

### ISSUE THREAD

**Issue by shaked-sapir** [TechnionYP5779/Team5-Fitnesspeaker#104]
Once the user logs some food, after responsd with "logged successfully" tell the user a tip, such as "drink a cup of water before the meal/now, make sure you eat while sitting , eat slowly..."

these phrases should be told randomly , once every 3-4 interactions with the app.

**Comment by LiorBenYamin** [comment]
Done. in the future we are planning to expand this feature, and save the user behavior.
