### ISSUE TITLE
Contact a dietitian

### ISSUE THREAD

**Issue by shaked-sapir** [TechnionYP5779/Team5-Fitnesspeaker#34]
search for a dietitian to work with- contact her and ask her request from our product as a customer of us. Ask Yossi first the requirements frm a customer

**Comment by NirChachmovitz** [comment]
Contacted a dietitian which is more than happy to support us and be our costumer.
Also, we contacted another dietitian and we are waiting for his approval.
If needed, a wanted ad will be published in a group of dietitians in Facebook by the group's admin.
