### ISSUE TITLE
refactor user info class

### ISSUE THREAD

**Issue by shalev-kuba** [TechnionYP5779/Team5-Fitnesspeaker#60]
![whatsapp image 2018-12-25 at 18 51 26](https://user-images.githubusercontent.com/34859568/50425007-4e578600-0877-11e9-8efa-87aab9661590.jpeg)

**Comment by LiorBenYamin** [comment]
The userInfo class contains details about the user that are changed once in a long while:
* age
* gender
* height
* goals of calories/proteins/cups of water per day
* limit of cigarettes per day
