### ISSUE TITLE
connect a Slot type to a built-in type -without customize-

### ISSUE THREAD

**Issue by shaked-sapir** [TechnionYP5779/Team5-Fitnesspeaker#7]
we need to make our "Food" Slot-type to be the "AMZAON.Food" built-in type, so we can get a lot of foods from that database, right now we can only customize an extension for it, and only use its values (instead of the original one's)

**Comment by shalev-kuba** [comment]
in any case we search the received string in the nutrition database.
so if there is no match there, we will enable the option to insert custom food manualy.
so this issue is not relevant.

**Comment by shalev-kuba** [comment]
was done with [this](https://github.com/TechnionYP5779/Team5-Diet-Tracker/commit/06083140801b17022777ae449ddc488394c97bda) commit
