### ISSUE TITLE
Build a database for User-info

### ISSUE THREAD

**Issue by shaked-sapir** [TechnionYP5779/Team5-Fitnesspeaker#9]
Build a database holding the user's information.
For the prototype, this will include the following:

personal info:
user_gender, user_age, user_weight

personal "food" info:
daily_calories, daily_goal_of_calories,
daily_amount_of_water, goal_for_daily_amount_of_water

**Comment by LiorBenYamin** [comment]
we decided to split the user info to 2 objects: daily info, and user info

**Comment by LiorBenYamin** [comment]
we opened 2 new issues #60 and #61 that closes this one
